homedir=getenv('HOME');


CXX='"g++-4.4"';
CC='"gcc-4.4"';

COLPACK_INCLUDES=' -I/home/erlenda/libs/eigen -I/home/erlenda/libs/ColPack-1.0.9/GraphColoring -I/home/erlenda/libs/ColPack-1.0.9/Utilities -I/home/erlenda/libs/ColPack-1.0.9/Main -I/home/erlenda/libs/ColPack-1.0.9/BipartiteGraphBicoloring -I/home/erlenda/libs/ColPack-1.0.9/BipartiteGraphPartialColoring -I/home/erlenda/libs/ColPack-1.0.9/Recovery ';
EIGEN_INCLUDES=' -I/home/anne/erlenda/libs/eigen ';
BASIC_INCLUDES = ' -I. ';

COLPACK_LIBRARY=' /home/erlenda/libs/ColPack-1.0.9/.libs/libColPack.a ';

CXXFLAGS = strcat('CXXFLAGS=','"\$CXXFLAGS',COLPACK_INCLUDES,EIGEN_INCLUDES,BASIC_INCLUDES,'"');

CXXOPTIMFLAGS='"-O2 -DNDEBUG"';
LDOPTIMFLAGS='"-O2 -fopenmp"';

ADD_ARGS='-v -largeArrayDims';


mexArgs1=strcat(CXXFLAGS,CXXOPTIMFLAGS,LDOPTIMFLAGS,ADD_ARGS)

mex $mexArgs1






% mex CXX="g++-4.4" CC="gcc-4.4" ...
%     CXXFLAGS="\$CXXFLAGS -I. -I/home/anne/erlenda/libs/eigen -I/home/anne/erlenda/libs/arprec-2.2.7/include -I/home/anne/erlenda/libs/ColPack/build/include -fopenmp" ...
%     -v -largeArrayDims CXXOPTIMFLAGS="-O2 -DNDEBUG" ... 
%     LDOPTIMFLAGS="-O2 -fopenmp"  matlab_wrap_eigen_det_app.cpp ...
%     ../../ratApps/libRatApps.a /home/anne/erlenda/libs/ColPack/libColPack.a ...
%     ../../lanczos/eigen/ap.o ../../lanczos/eigen/linalg.o ../../lanczos/eigen/alglibinternal.o ../../lanczos/eigen/alglibmisc.o


mex CXX="g++-4.4" CC="gcc-4.4" ...
    CXXFLAGS="\$CXXFLAGS -I. -I/home/anne/erlenda/libs/eigen -I/home/anne/erlenda/libs/ColPack/build/include -fopenmp" ...
    -v -largeArrayDims CXXOPTIMFLAGS="-O2 -DNDEBUG" ... 
    LDOPTIMFLAGS="-O2 -fopenmp"  matlab_wrap_probing_vector.cpp ...
    /home/anne/erlenda/libs/ColPack/libColPack.a

% mex CXX="g++-4.3" CC="gcc-4.3" ...
%     CXXFLAGS="\$CXXFLAGS -I. -I/home/anne/erlenda/libs/eigen -fopenmp" ...
%     -v -largeArrayDims CXXOPTIMFLAGS="-O2 -DNDEBUG" ... 
%     LDOPTIMFLAGS="-O2 -fopenmp"  matlab_wrap_compute_shifts.cpp

% mex CXX="g++-4.4" CC="gcc-4.4" ...
%     CXXFLAGS="\$CXXFLAGS -I. -I/home/anne/erlenda/libs/eigen -I/home/anne/erlenda/libs/arprec-2.2.7/include -I/home/anne/erlenda/libs/ColPack/build/include -fopenmp" ...
%     -v -largeArrayDims CXXOPTIMFLAGS="-O2 -DNDEBUG" ... 
%     LDOPTIMFLAGS="-O2 -fopenmp"  matlab_wrap_det_app_base.cpp ...
%     ../../ratApps/libRatApps.a /home/anne/erlenda/libs/ColPack/libColPack.a ...
%     ../../lanczos/eigen/ap.o ../../lanczos/eigen/linalg.o ../../lanczos/eigen/alglibinternal.o ../../lanczos/eigen/alglibmisc.o

% mex CXX="g++-4.3" CC="gcc-4.3" ...
%     CXXFLAGS="\$CXXFLAGS -I. -I/home/anne/erlenda/libs/eigen -I/home/anne/erlenda/libs/arprec-2.2.7/include -I/home/anne/erlenda/libs/ColPack/build/include -fopenmp" ...
%     -v -largeArrayDims CXXOPTIMFLAGS="-O2 -DNDEBUG" ... 
%     LDOPTIMFLAGS="-O2 -fopenmp"  matlab_wrap_lanczos_eigenvals.cpp ...
%     ../../ratApps/libRatApps.a /home/anne/erlenda/libs/ColPack/libColPack.a ...
%     ../../lanczos/eigen/ap.o ../../lanczos/eigen/linalg.o ../../lanczos/eigen/alglibinternal.o ../../lanczos/eigen/alglibmisc.o

mex CXX="g++-4.4" CC="gcc-4.4" ...
    CXXFLAGS="\$CXXFLAGS -I. -I/home/anne/erlenda/libs/eigen -I/home/anne/erlenda/libs/arprec-2.2.7/include -I/home/anne/erlenda/libs/ColPack/build/include -fopenmp" ...
    -v -largeArrayDims CXXOPTIMFLAGS="-O2 -DNDEBUG" ... 
    LDOPTIMFLAGS="-O2 -fopenmp"  matlab_wrap_margvars.cpp ...
    ../../ratApps/libRatApps.a /home/anne/erlenda/libs/ColPack/libColPack.a ...
    ../../lanczos/eigen/ap.o ../../lanczos/eigen/linalg.o ../../lanczos/eigen/alglibinternal.o ../../lanczos/eigen/alglibmisc.o

mex CXX="g++-4.4" CC="gcc-4.4" ...
    CXXFLAGS="\$CXXFLAGS -I. -I/home/anne/erlenda/libs/eigen -I/home/anne/erlenda/libs/arprec-2.2.7/include -I/home/anne/erlenda/libs/ColPack/build/include -fopenmp" ...
    -v -largeArrayDims CXXOPTIMFLAGS="-O2 -DNDEBUG" ... 
    LDOPTIMFLAGS="-O2 -fopenmp"  matlab_wrap_margvars_duplicateQ.cpp ...
    ../../ratApps/libRatApps.a /home/anne/erlenda/libs/ColPack/libColPack.a ...
    ../../lanczos/eigen/ap.o ../../lanczos/eigen/linalg.o ../../lanczos/eigen/alglibinternal.o ../../lanczos/eigen/alglibmisc.o