% homedir=getenv('HOME');


% mex CXX="g++-4.3" CC="gcc-4.3" ...
%     CXXFLAGS="\$CXXFLAGS -I. -I/home/anne/erlenda/libs/eigen -I/home/anne/erlenda/libs/arprec-2.2.7/include -I/home/anne/erlenda/libs/ColPackg++-4.3.4/build/include -fopenmp" ...
%     -v -largeArrayDims CXXOPTIMFLAGS="-O2 -DNDEBUG" ... 
%     LDOPTIMFLAGS="-O2 -fopenmp"  matlab_wrap_eigen_det_app.cpp ...
%     ../../ratApps/libRatApps.a /home/anne/erlenda/libs/ColPackg++-4.3.4/libColPack.a ...
%     ../../lanczos/eigen/ap.o ../../lanczos/eigen/linalg.o ../../lanczos/eigen/alglibinternal.o ../../lanczos/eigen/alglibmisc.o


% mex CXX="g++-4.3" CC="gcc-4.3" ...
%     CXXFLAGS="\$CXXFLAGS -I. -I/home/anne/erlenda/libs/eigen -I/home/anne/erlenda/libs/ColPackg++-4.3.4/build/include -fopenmp" ...
%     -v -largeArrayDims CXXOPTIMFLAGS="-O2 -DNDEBUG" ... 
%     LDOPTIMFLAGS="-O2 -fopenmp"  matlab_wrap_probing_vector.cpp ...
%     /home/anne/erlenda/libs/ColPackg++-4.3.4/libColPack.a
% 
% mex CXX="g++-4.3" CC="gcc-4.3" ...
%     CXXFLAGS="\$CXXFLAGS -I. -I/home/anne/erlenda/libs/eigen -fopenmp" ...
%     -v -largeArrayDims CXXOPTIMFLAGS="-O2 -DNDEBUG" ... 
%     LDOPTIMFLAGS="-O2 -fopenmp"  matlab_wrap_compute_shifts.cpp

% mex CXX="g++-4.4" CC="gcc-4.4" ...
%     CXXFLAGS="\$CXXFLAGS -I. -I/home/anne/erlenda/libs/eigen -I/home/anne/erlenda/libs/arprec-2.2.7/include -I/home/anne/erlenda/libs/ColPackg++-4.3.4/build/include -fopenmp" ...
%     -v -largeArrayDims CXXOPTIMFLAGS="-O2 -DNDEBUG" ... 
%     LDOPTIMFLAGS="-O2 -fopenmp"  matlab_wrap_det_app_base.cpp ...
%     ../../ratApps/libRatApps.a /home/anne/erlenda/libs/ColPackg++-4.3.4/libColPack.a ...
%     ../../lanczos/eigen/ap.o ../../lanczos/eigen/linalg.o ../../lanczos/eigen/alglibinternal.o ../../lanczos/eigen/alglibmisc.o

% mex CXX="g++-4.3" CC="gcc-4.3" ...
%     CXXFLAGS="\$CXXFLAGS -I. -I/home/anne/erlenda/libs/eigen -I/home/anne/erlenda/libs/arprec-2.2.7/include -I/home/anne/erlenda/libs/ColPackg++-4.3.4/build/include -fopenmp" ...
%     -v -largeArrayDims CXXOPTIMFLAGS="-O2 -DNDEBUG" ... 
%     LDOPTIMFLAGS="-O2 -fopenmp"  matlab_wrap_lanczos_eigenvals.cpp ...
%     ../../ratApps/libRatApps.a /home/anne/erlenda/libs/ColPackg++-4.3.4/libColPack.a ...
%     ../../lanczos/eigen/ap.o ../../lanczos/eigen/linalg.o ../../lanczos/eigen/alglibinternal.o ../../lanczos/eigen/alglibmisc.o

mex CXX="g++-4.4" CC="gcc-4.4" ...
    CXXFLAGS="\$CXXFLAGS -I. -I/home/anne/erlenda/libs/eigen -I/home/anne/erlenda/libs/arprec-2.2.7/include -I/home/anne/erlenda/libs/ColPackg++-4.3.4/build/include -fopenmp" ...
    -v -largeArrayDims CXXOPTIMFLAGS="-O2 -DNDEBUG" ... 
    LDOPTIMFLAGS="-O2 -fopenmp"  matlab_wrap_margvars.cpp ...
    ../../ratApps/libRatApps.a /home/anne/erlenda/libs/ColPackg++-4.3.4/libColPack.a ...
    ../../lanczos/eigen/ap.o ../../lanczos/eigen/linalg.o ../../lanczos/eigen/alglibinternal.o ../../lanczos/eigen/alglibmisc.o

% mex CXX="g++-4.4" CC="gcc-4.4" ...
%     CXXFLAGS="\$CXXFLAGS -I. -I/home/anne/erlenda/libs/eigen -I/home/anne/erlenda/libs/arprec-2.2.7/include -I/home/anne/erlenda/libs/ColPackg++-4.3.4/build/include -fopenmp" ...
%     -v -largeArrayDims CXXOPTIMFLAGS="-O2 -DNDEBUG" ... 
%     LDOPTIMFLAGS="-O2 -fopenmp"  matlab_wrap_margvars_duplicateQ.cpp ...
%     ../../ratApps/libRatApps.a /home/anne/erlenda/libs/ColPackg++-4.3.4/libColPack.a ...
%     ../../lanczos/eigen/ap.o ../../lanczos/eigen/linalg.o ../../lanczos/eigen/alglibinternal.o ../../lanczos/eigen/alglibmisc.o